version: "2"
services:
  traefik:
    image: traefik
    command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "90:80"
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD= supersecret
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
  backend1:
    image: systelab/seed-jee:latest
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=3"
      - "traefik.weight=1"
      - "traefik.port=8080"
      - "traefik.backend.loadbalancer.method=wrr"
    depends_on:
      - db
    environment:
      - MYSQL_URI=db:3306
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
  backend2:
    image: systelab/seed-jee:latest
    labels:
      - "traefik.frontend.rule=PathPrefix:/"
      - "traefik.frontend.priority=1"
      - "traefik.weight=1"
      - "traefik.port=8080"
      - "traefik.backend.loadbalancer.method=wrr"
    depends_on:
      - db
    environment:
      - MYSQL_URI=db:3306
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=SEED
      - MYSQL_USER=SEED
      - MYSQL_PASSWORD=SEED
  frontent1:
    image: systelab/seed-angular:latest
    ports:
      - "80:80"
    depends_on:
      - traefik
    environment:
      - BACKEND=http://127.0.0.1:90
